# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

IsingSamplerCpp <- function(n, graph, thresholds, beta, nIter, responses, exact) {
    .Call('IsingSampler_IsingSamplerCpp', PACKAGE = 'IsingSampler', n, graph, thresholds, beta, nIter, responses, exact)
}

H <- function(J, s, h) {
    .Call('IsingSampler_H', PACKAGE = 'IsingSampler', J, s, h)
}

