# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

IsingProcess <- function(nSample, graph, thresholds, beta, responses) {
    .Call('IsingSampler_IsingProcess', PACKAGE = 'IsingSampler', nSample, graph, thresholds, beta, responses)
}

IsingSamplerCpp <- function(n, graph, thresholds, beta, nIter, responses, exact, constrain) {
    .Call('IsingSampler_IsingSamplerCpp', PACKAGE = 'IsingSampler', n, graph, thresholds, beta, nIter, responses, exact, constrain)
}

H <- function(J, s, h) {
    .Call('IsingSampler_H', PACKAGE = 'IsingSampler', J, s, h)
}

f <- function(Y, J, h) {
    .Call('IsingSampler_f', PACKAGE = 'IsingSampler', Y, J, h)
}

Hvec <- function(s, Theta, N) {
    .Call('IsingSampler_Hvec', PACKAGE = 'IsingSampler', s, Theta, N)
}

